name: CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@main
    - name: Start xcodebuild test
      run: |
        xcodebuild -workspace GimmiekCore -scheme Core
        xcodebuild -list
        xcodebuild clean build -workspace "GimmiekCore.xcworkspace" -scheme Core

