name: CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@main
    - name: Start xcodebuild test
      run: xcodebuild clean build -workspace "GimmiekCore" -scheme Core

