name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@main
    - name: Start xcodebuild test
      run: xcodebuild clean build
